### ISSUE TITLE
[FE] Distributor - Connect with Nostr

### ISSUE THREAD

**Issue by zhivkoangelov** [growr-xyz/bitcoin-street-store-agent-app#3]

**Comment by radoystoyanov** [comment]
Integrated the following features:
- Implemented UserContext provider
- Connect with Nostr via browser extension (e.g. Alby) – get the npub (public key)
- Sign a NIP-98 event for API authentication and attach to default axios headers
- Automatically initiate re-sigining of the NIP-98 event before expiration (currently set to 10 minutes)
- Retrieve Nostr profile event (kind 0) and set user profile metadata such as name & picture
